# Generated by Django 4.1.3 on 2022-11-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_veryfypassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('verify', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
