# Generated by Django 4.1.3 on 2022-11-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verifymobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifymobile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
