# Generated by Django 4.1.3 on 2022-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password', models.CharField(max_length=26)),
                ('new_password', models.CharField(max_length=26)),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
