# Generated by Django 4.1.3 on 2022-12-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_user_blog_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_mnodified',
            new_name='date_modified',
        ),
    ]
